# Generated by Django 3.2 on 2022-11-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(default=None, max_length=30)),
                ('add_time', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=32)),
                ('disease', models.CharField(max_length=200)),
                ('pulse_rate', models.TextField(max_length=30, null=True)),
                ('blood_pressure_up', models.TextField(max_length=30, null=True)),
                ('blood_pressure_down', models.TextField(max_length=30, null=True)),
                ('temperature', models.TextField(max_length=30, null=True)),
                ('weight', models.TextField(max_length=30, null=True)),
                ('disease_1', models.BooleanField(default=False)),
                ('disease_2', models.BooleanField(default=False)),
                ('disease_3', models.BooleanField(default=False)),
                ('disease_4', models.BooleanField(default=False)),
                ('disease_5', models.BooleanField(default=False)),
                ('disease_1_index', models.CharField(default='0', max_length=30)),
                ('disease_2_index', models.CharField(default='1', max_length=30)),
                ('disease_3_index', models.CharField(default='2', max_length=30)),
                ('disease_4_index', models.CharField(default='3', max_length=30)),
                ('disease_5_index', models.CharField(default='4', max_length=30)),
                ('cc_time', models.DateTimeField(auto_now=True)),
                ('r_time', models.TextField(default='', null=True)),
                ('r_time_d', models.TextField(default='', null=True)),
                ('r_pulse_rate', models.TextField(default='', null=True)),
                ('r_blood_pressure_up', models.TextField(default='', null=True)),
                ('r_blood_pressure_down', models.TextField(default='', null=True)),
                ('r_temperature', models.TextField(default='', null=True)),
                ('r_weight', models.TextField(default='', null=True)),
                ('r_disease', models.TextField(default='', null=True)),
            ],
            options={
                'verbose_name': 'Patients',
                'ordering': ['-cc_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('identity', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('patient_num', models.CharField(default='0', max_length=30)),
                ('pid_data', models.TextField(default='', null=True)),
            ],
            options={
                'verbose_name': 'Users',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('frequency', models.TextField(default='1', null=True)),
                ('method', models.TextField(default='', null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('cid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='PHR.patient')),
            ],
            options={
                'verbose_name': 'drug_name',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='PHR.user'),
        ),
    ]
