# Generated by Django 3.2 on 2022-06-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('identity', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Users',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PHR.user')),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=32)),
                ('disease', models.CharField(max_length=200)),
                ('heart_rate', models.TextField(max_length=30, null=True)),
                ('blood_pressure', models.TextField(max_length=30, null=True)),
                ('temperature', models.TextField(max_length=30, null=True)),
                ('weight', models.TextField(max_length=30, null=True)),
                ('cc_time', models.DateTimeField(auto_now=True)),
                ('r_time', models.TextField(default='', null=True)),
                ('r_heart_rate', models.TextField(default='', null=True)),
                ('r_blood_pressure', models.TextField(default='', null=True)),
                ('r_temperature', models.TextField(default='', null=True)),
                ('r_weight', models.TextField(default='', null=True)),
            ],
            options={
                'verbose_name': 'Patients',
                'ordering': ['-c_time'],
            },
            bases=('PHR.user',),
        ),
    ]
