# Generated by Django 3.2 on 2022-07-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blood_pressure',
            new_name='blood_pressure_down',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='r_blood_pressure',
            new_name='r_blood_pressure_down',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure_up',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='r_blood_pressure_up',
            field=models.TextField(default='', null=True),
        ),
    ]
